<#ftl output_format="XML" encoding="iso-8859-1">
<?xml version="1.0" encoding="iso-8859-1" ?>
<TOURNAMENTTV ClubName="Råda BMK" VERSION="2020.1">
<ITEMS>
  <ITEM ITEMTYPE="13" FILENAME="" DURATION="45" MAXNUMITEMS="10" DISPLAYORDER="1" FLAGS="1" TITLE="Match Overview" FONTCOLOR="0" LINECOLOR="0" HEADERHEIGHT="0" FOOTERHEIGHT="0" COLUMNS="1" ROWS="1"></ITEM>
  <ITEM ITEMTYPE="0" FILENAME="" DURATION="15" MAXNUMITEMS="10" DISPLAYORDER="2" FLAGS="0" TITLE="Bästa klubb" FONTCOLOR="0" LINECOLOR="0" HEADERHEIGHT="0" FOOTERHEIGHT="0" COLUMNS="1" ROWS="1">
   <CONTENT><![CDATA[${body}]]></CONTENT>
</ITEM>
</ITEMS>
</TOURNAMENTTV>